//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.strava.api.tests.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.strava.api.tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;id&quot;: 227615,
        ///  &quot;resource_state&quot;: 3,
        ///  &quot;firstname&quot;: &quot;John&quot;,
        ///  &quot;lastname&quot;: &quot;Applestrava&quot;,
        ///  &quot;profile_medium&quot;: &quot;http://pics.com/227615/medium.jpg&quot;,
        ///  &quot;profile&quot;: &quot;http://pics.com/227615/large.jpg&quot;,
        ///  &quot;city&quot;: &quot;San Francisco&quot;,
        ///  &quot;state&quot;: &quot;California&quot;,
        ///  &quot;country&quot;: &quot;United States&quot;,
        ///  &quot;sex&quot;: &quot;M&quot;,
        ///  &quot;friend&quot;: null,
        ///  &quot;follower&quot;: null,
        ///  &quot;premium&quot;: true,
        ///  &quot;created_at&quot;: &quot;2008-01-01T17:44:00Z&quot;,
        ///  &quot;updated_at&quot;: &quot;2013-09-04T20:00:50Z&quot;,
        ///  &quot;follower_count&quot;: 273,
        ///  &quot;friend_count&quot;: 19,
        ///  &quot;mutual_frien [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AthleteJson {
            get {
                return ResourceManager.GetString("AthleteJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///    &quot;id&quot;: &quot;b814946&quot;,
        ///    &quot;primary&quot;: true,
        ///    &quot;name&quot;: &quot;Canyon Roadlite AL 7.0&quot;,
        ///    &quot;resource_state&quot;: 3,
        ///    &quot;distance&quot;: 8751520.7,
        ///    &quot;brand_name&quot;: &quot;Canyon&quot;,
        ///    &quot;model_name&quot;: &quot;Roadlite AL 7.0&quot;,
        ///    &quot;frame_type&quot;: 3,
        ///    &quot;description&quot;: &quot;&quot;
        ///} ähnelt.
        /// </summary>
        internal static string GearJson {
            get {
                return ResourceManager.GetString("GearJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///
        ///    &quot;effort_count&quot;: 8774,
        ///    &quot;entry_count&quot;: 8774,
        ///    &quot;entries&quot;: [
        ///        {
        ///            &quot;athlete_name&quot;: &quot;Jim Whimpey&quot;,
        ///            &quot;athlete_id&quot;: 123529,
        ///            &quot;athlete_gender&quot;: &quot;M&quot;,
        ///            &quot;average_hr&quot;: 190.5,
        ///            &quot;average_watts&quot;: 460.8,
        ///            &quot;distance&quot;: 2659.9,
        ///            &quot;elapsed_time&quot;: 360,
        ///            &quot;moving_time&quot;: 360,
        ///            &quot;start_date&quot;: &quot;2013-03-29T13:49:35Z&quot;,
        ///            &quot;start_date_local&quot;: &quot;2013-03-29T06:49:35Z&quot;,
        ///            &quot;activity_id&quot;: 4632 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LeaderboardJson {
            get {
                return ResourceManager.GetString("LeaderboardJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;id&quot;: 269990681,
        ///  &quot;resource_state&quot;: 3,
        ///  &quot;name&quot;: &quot;Geysers Road Climb&quot;,
        ///  &quot;segment&quot;: {
        ///    &quot;id&quot;: 1818385,
        ///    &quot;resource_state&quot;: 2,
        ///    &quot;name&quot;: &quot;Geysers Road Climb&quot;,
        ///    &quot;activity_type&quot;: &quot;Ride&quot;,
        ///    &quot;distance&quot;: 6001.74,
        ///    &quot;average_grade&quot;: 6.24152,
        ///    &quot;maximum_grade&quot;: 23.5131,
        ///    &quot;elevation_high&quot;: 745.6,
        ///    &quot;elevation_low&quot;: 371.0,
        ///    &quot;start_latlng&quot;: [
        ///      38.810384860262275,
        ///      -122.85571538843215
        ///    ],
        ///    &quot;end_latlng&quot;: [
        ///      38.79168709740043,
        ///      -122.82848568633199        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string SegmentEffortJson {
            get {
                return ResourceManager.GetString("SegmentEffortJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;id&quot;: 229781,
        ///  &quot;resource_state&quot;: 3,
        ///  &quot;name&quot;: &quot;Hawk Hill&quot;,
        ///  &quot;activity_type&quot;: &quot;Ride&quot;,
        ///  &quot;distance&quot;: 2684.82,
        ///  &quot;average_grade&quot;: 5.7,
        ///  &quot;maximum_grade&quot;: 14.2,
        ///  &quot;elevation_high&quot;: 245.3,
        ///  &quot;elevation_low&quot;: 92.4,
        ///  &quot;start_latlng&quot;: [
        ///    37.8331119,
        ///    -122.4834356
        ///  ],
        ///  &quot;end_latlng&quot;: [
        ///    37.8280722,
        ///    -122.4981393
        ///  ],
        ///  &quot;start_latitude&quot;: 37.8331119,
        ///  &quot;start_longitude&quot;: -122.4834356,
        ///  &quot;end_latitude&quot;: 37.8280722,
        ///  &quot;end_longitude&quot;: -122.4981393,
        ///  &quot;climb_category&quot;: 1,
        ///  &quot;city [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string SegmentJson {
            get {
                return ResourceManager.GetString("SegmentJson", resourceCulture);
            }
        }
    }
}
